
spring:
  application:
    name: sample-application

rocket-mq:
  name-server: 122.51.171.126:9876
  provider:
    group: TEST_SAMPLE_01_P_GROUP
    sample-provider:
      topic: TEST_SAMPLE_01
  consumer:
    sample-consumer:
      trace: false
      customized-trace-topic: qaz
      topic: TEST_SAMPLE_01
      group: TEST_SAMPLE_01_C_GROUP

compensate:
  CompensateSimpleService:
    compensate-type: 0
    retry-rule: 10s
    alarm-rule: 10s ...