
spring:
  application:
    name: sample-application

rocket-mq:
  name-server: 122.51.171.126:9876
  access-channel:
  provider:
    group:
    send-msg-timeout:
    sample-provider:
      topic: TEST_SAMPLE_01
